### PR TITLE
Add clang-format support #181

### PR DESCRIPTION
**Pull request by mortbopet**
This commit adds support for running clang-format on C source code. `clang-format` must be available in PATH.

### CODE REVIEW

**Comment by mortbopet** [comment]
@lcgamboa do you mind trying this out before i merge it?

**Comment by lcgamboa** [comment]
I have tested here on Linux on various files and it worked without any problems.
Some doubts:
If clang-format is not available what happens?
Is it possible to choose the executable path? (Or use another one formatter ?)

**Comment by mortbopet** [comment]
> If clang-format is not available what happens?
Nothing will happen.

> Is it possible to choose the executable path?
At the moment no, but i can work that in. 

> (Or use another one formatter ?)
Currently, no. The issue with using a formatter integrated into an IDE is that the formatter needs to provide some form of curser mapping support (if the cursor was at position x before formatting, where should it be after formatting, so as to maintain its position in the code?). [clang-format](https://clang.llvm.org/docs/ClangFormat.html) has the `--cursor` argument which i use for this. I am unsure about other formatters, but there probably needs to be specialized handling for each formatter type. Which is why things are limited to clang-format for now.

**Comment by mortbopet** [comment]
Added option to set clang-format executable as well as modified where the temporary file is being generated, such that clang-format will use any .clang-format file in the source file directory, if available.

**Pull request merged**
