### PR TITLE
Adjust splitter regex to allow parentheses

### LINKED ISSUE #10: Allow for '(' and ')' characters to exist in a label declaration
Allowing for this would make us not have to remove the function argument type when inserting RISC-V compiled code from compiler explorer.

The issue lies with the default splitter regex that is used in syntaxhighlighter.cpp in checkSyntax()

### PR DESCRIPTION
**Pull request by kylelaker**
This regex is a bit of a kludge and has several non-capturing groups as well as some lookaheads. It also wouldn't accept the floating point registers (but my understanding is that support for RV32F/RV32D is not available yet).

If a type has the same name as a register, then this will break. I am unsure of how that can be avoided without more complex changes than to just the regex. Hopefully in Compiler Explorer examples, that wouldn't be an issue.

Resolves #10

### CODE REVIEW

**Comment by kylelaker** [comment]
It seems like some adjustment will be necessary to `lexerutils.h:splitQuotes`

**Comment by mortbopet** [comment]
Is this still WIP?

**Comment by kylelaker** [comment]
It is. So it works for functions with one argument but not for anything with a comma. That will require changes to `lexerUtils.h:splitQuotes` and I'm not really sure how to go about that. I have an idea that maybe parenthesis can be treated like quotes if the regex is correct but I need to play around with that a little more.

**Comment by kylelaker** [comment]
Alright, I think with these fixes to `splitQuotes`, it should be set. Let me know if there is an edge case I didn't consider that this breaks.

**Comment by kylelaker** [comment]
Let me know if there are any more changes you'd like to see to this in order for it to be merged

**Comment by mortbopet** [comment]
Looks good to me, will merge

**Pull request merged**
