### PR TITLE
Add support for variable length instructions in the InstructionModel

### PR DESCRIPTION
**Pull request by lcgamboa**
Related to https://github.com/mortbopet/Ripes/issues/127

### CODE REVIEW

**Comment by lcgamboa** [comment]
Unfortunately my old netbeans 8.2 doesn't have support to integrate clang-format. 
I've tried switching to vscode before, but I still find netbeans debugging support much better.
I will use git-clang-format from now.

**Comment by mortbopet** [comment]
Looks like there's some CI issues that have been exposed by this PR; i'm working on the problem, and ping you once things are fixed!

**Comment by mortbopet** [comment]
Would you mind rebasing your PRs onto the head of `c_ext` and re-push these PRs? apologies for the inconvenience.

**Comment by mortbopet** [comment]
Copying in the comment from the other thread:

---
great progress! My initial thought is that it seems like the implementation is RISC-V-dependent. Now, this doesn't matter in the current state of Ripes (since only RISC-V is supported). However, code should in general work in an ISA-agnostic manner, such that we don't have to rewrite the entire UI whenever we switch to processors of other ISAs. If you find that there's some functionality lacking in the [ISAInfo](https://github.com/mortbopet/Ripes/blob/master/src/isa/isainfo.h#L28) interface, then we should brainstorm on this.

As suggested in my initial post, a disassembly result contains both the disassembled string as well as the number of bytes disassembled (instruction width). I imagine that this (somehow) can help with the "index-to-address" logic.
https://github.com/mortbopet/Ripes/blob/7ec2c53e4f5813ae4ccb6620e932b3251f83f367/src/assembler/assemblerbase.h#L14-L21

**Comment by lcgamboa** [comment]
In the current structure the indexToAddress method is called to pass the address to the disassembleInstr method. The disassembleInstr method does not use instruction length information. 
I can change the code to use the disassembleInstr method to get indexToAddress and make the code ISA-agnostic as you suggested. I believe that using sdt:map to store the addresses of the instructions will solve the indexToAddress method optimization problem, but it will consume more memory. Today my vacation is over and this week my little son doesn't go to school, so I'm going to work more slowly.

**Pull request merged**
