### PR TITLE
Add docker recipe

### PR DESCRIPTION
**Pull request by matsievskiysv**
Add recipe to build and run Ripes from the docker image.

### CODE REVIEW

**Comment by matsievskiysv** [comment]
I've created a workflow for building a docker image and uploading it to DockerHub.
In order to use it you'll need
1. Create `DOCKERHUB_USERNAME` and `DOCKERHUB_TOKEN` secrets with your dockerhub credentials
1. Adjust user the last line in `.github/workflows/docker-build.yml`: substitute `matsievskiysv` with your dockerhub username

> for testing this in CI

A subset of tests (which don't need X) are executed after build so if build or tests fail, workflow would also fail.

**Comment by mortbopet** [comment]
Awesome, I've created an account at dockerhub and added the necessary secrets. I'll go ahead and merge and then we'll take it from there based on whether things work.

**Comment by matsievskiysv** [comment]
> and added the necessary secrets

You should also change the tag.
FYI, this workflow can be started manually form actions page if needed.

**Comment by mortbopet** [comment]
Should be settled now https://hub.docker.com/r/mortbopet/ripes.
Thank you very much for the contribution!

**Pull request merged**
